import { createSlice } from '@reduxjs/toolkit';

import DataFrame from 'dataframe-js';

const initialState = {
    table: []
};

export const blupTableSlice = createSlice({
    name: 'blupTable',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        setBlupTableData: (state, action) => {
            state.table = action.payload
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: {}
});

/* Action creators -- wrapping fundamental list elements */
export const { setBlupTableData } = blupTableSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectBlupTableData = (state) => state.blupTable.table;

export default blupTableSlice.reducer;
