import { createSlice } from '@reduxjs/toolkit';

import DataFrame from 'dataframe-js';

const initialState = {
    filters: [],
};

export const blupTableGridSlice = createSlice({
    name: 'blupTableGrid',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        setBlupTableGridFilters: (state, action) => {
            state.filters = action.payload
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: {}
});

/* Action creators -- wrapping fundamental list elements */
export const { setBlupTableGridFilters } = blupTableGridSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectBlupTableGridFilters = (state) => state.blupTableGrid.filters;

export default blupTableGridSlice.reducer;
