import { createSlice } from '@reduxjs/toolkit';

const initialState = {
    traits: []
};

export const corrPlotSlice = createSlice({
    name: 'corrPlot',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        setCorrPlotTraits: (state, action) => {
            state.traits = action.payload
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: {}
});

/* Action creators -- wrapping fundamental list elements */
export const { setCorrPlotTraits } = corrPlotSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectCorrPlotTraits = (state) => state.corrPlot.traits;

export default corrPlotSlice.reducer;
