import { createSlice } from '@reduxjs/toolkit';

const initialState = {
    transform: {x: 0, y: 0, k: 1},
};

export const viewSlice = createSlice({
    name: 'view',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        setTransform: (state, action) => {
            state.transform = action.payload;
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: {}
});

/* Action creators -- wrapping fundamental list elements */
export const { setTransform } = viewSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectTransform = (state) => state.view.transform;

export default viewSlice.reducer;
