# Abstract {-}

The American cranberry (_Vaccinium macrocarpon Ait._) was domesticated around 200 years ago, and 
for over a century of this domestication, breeders had traditionally assessed traits based on “upright” 
(reproductive branch) data in order to evaluate genotype performance and make selections. Currently, due 
to their increased efficiency, cranberry breeding programs are rapidly moving towards high-throughput phenotyping 
techniques, and there is a need to evaluate the usefulness of traditional phenotyping techniques to determine which 
traits are relevant to modern cranberry breeding programs. From 2011 to 2014, 22 fruiting upright-based traits, 
10 uprights per genotype, were collected from two half-sib breeding populations planted at the 
Rutgers University P.E. Marucci Center in Chatsworth, NJ, USA.  Over the same time period, eight additional 
plot-sampled traits were collected for yield, rot, and chemistry in order to compare modern metrics against
more classically-based upright phenotypes.  Mixed models were used to estimate 
genotype BLUP values for all traits, factoring in effects such as year and spatial field differences, along
with model augmentation using marker-derived genotype relationship matrices.  Using the R *qtl* package, both standard interval 
mapping and multiple-QTL model fit and selection approaches found significant marker-BLUP associations, with QTL fit against a 
high-density, multi-population composite linkage map.  Comparative analysis was performed using QTL derived from traits collected using newer methods on the same population.
