import { createSlice } from '@reduxjs/toolkit';
const initialState = {
    plotData: {
        data: [],
        color: "rgba(0,0,0,1)",
        model: "",
        trait: "",
        chr: "",
        position: 0
    }
};

export const effectPlotSlice = createSlice({
    name: 'effectPlot',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        setEffectPlotData: (state, action) => {
            state.plotData = action.payload
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: {}
});

/* Action creators -- wrapping fundamental list elements */
export const { setEffectPlotData } = effectPlotSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectEffectPlotData = (state) => state.effectPlot.plotData;

export default effectPlotSlice.reducer;
